name: Maven TestNG Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 04 * * 1-5'

jobs:
  regression-test:
    runs-on: windows-latest
   
    steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'
          # - name: Run the Maven verify phase
            # run: mvn --batch-mode --update-snapshots verify
          - name: Build and run tests
            run: |
              mvn clean test -DsuiteXmlFile=testng.xml
