name: Maven TestNG Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 04 * * 1-5'

jobs:
  regression-test:
    runs-on: windows-latest
   
    steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'
          - name: Install dependencies
            run: mvn install -DskipTests
          - name: Build and run tests
            run: mvn clean test -DsuiteXmlFile=testng.xml _Dmaven.test.failure.ignore=true
          - name: Archive test results
            uses: actions/upload-artifact@v2
            with:
               name: testng-reports
               path: test-output
